import { GiftSessionResponse } from './api';

export const replaySession: GiftSessionResponse = {
  session_id: 'replay-long-distance-partners-2026',
  giver_id: 'person-maya',
  recipient_id: 'person-jordan',
  occasion_id: 'occasion-jordan-birthday-2026',
  next_stage: null,
  ledger: {
    session_id: 'replay-long-distance-partners-2026',
    authorship: 'hybrid',
    completed: true,
    stage_count: 6,
    counts: { accept: 1, edit: 1, regenerate: 1, delegate: 4, pending: 0, error: 0 },
    timeline: [
      { stage: 'recipient_profiling', actor: 'agent', action: 'pending', status: 'pending', timestamp: '2026-07-06T19:09:55.072Z', rationale: 'Uses Jordan’s stated and inferred preferences from the fixture.' },
      { stage: 'recipient_profiling', actor: 'human', action: 'edit', status: 'completed', timestamp: '2026-07-06T19:10:02.000Z', rationale: 'Human softened the profile toward warmth and playfulness.' },
      { stage: 'relationship_analysis', actor: 'agent', action: 'accept', status: 'completed', timestamp: '2026-07-06T19:10:10.000Z', rationale: 'The fixture gives a partner relationship with closeness 5/5.' },
      { stage: 'recommendation', actor: 'agent', action: 'regenerate', status: 'completed', timestamp: '2026-07-06T19:10:18.000Z', rationale: 'The first recommendation pass was rerun to emphasize the generated keepsake.' },
      { stage: 'recommendation', actor: 'agent', action: 'delegate', status: 'completed', timestamp: '2026-07-06T19:10:28.000Z', rationale: 'The ranking connects explicit preferences and shared memories to the birthday.' },
      { stage: 'creative_generation', actor: 'agent', action: 'delegate', status: 'completed', timestamp: '2026-07-06T19:10:35.000Z', rationale: 'Generated from the fixture memory context at a balanced agency setting.' },
      { stage: 'greeting_story', actor: 'agent', action: 'delegate', status: 'completed', timestamp: '2026-07-06T19:10:39.000Z', rationale: 'Uses two supplied memories and follows the close-partner tone guidance.' },
      { stage: 'delivery_planner', actor: 'agent', action: 'delegate', status: 'completed', timestamp: '2026-07-06T19:10:42.000Z', rationale: 'Uses simulated digital-card delivery; no purchase or shipment is created.' },
    ],
  },
  stage_log: [
    {
      stage: 'recipient_profiling',
      proposed_by: 'agent',
      output: {
        interests: [
          { name: 'urban sketching', confidence: 1 },
          { name: 'travel-poster illustration', confidence: 0.72 },
          { name: 'mustard yellow', confidence: 1 },
        ],
        communication_style: 'Warm, playful, and memory-rich.',
        gift_history_summary: 'No prior gift history was supplied.',
      },
      human_action: null,
      human_edit: null,
      confidence: 0.9,
      rationale: 'Uses Jordan’s stated and inferred preferences from the fixture.',
      timestamp: '2026-07-06T19:09:55.072Z',
      status: 'pending',
    },
    {
      stage: 'recipient_profiling',
      proposed_by: 'human',
      output: {
        interests: [
          { name: 'urban sketching', confidence: 1 },
          { name: 'travel-poster illustration', confidence: 0.72 },
          { name: 'mustard yellow', confidence: 1 },
        ],
        communication_style: 'Warm, playful, and memory-rich.',
        gift_history_summary: 'No prior gift history was supplied.',
      },
      human_action: 'edit',
      human_edit: { communication_style: 'Warm, playful, memory-rich, and a little less polished.' },
      confidence: 0.9,
      rationale: 'Human softened the profile toward warmth and playfulness.',
      timestamp: '2026-07-06T19:10:02.000Z',
      status: 'completed',
    },
    {
      stage: 'relationship_analysis',
      proposed_by: 'agent',
      output: {
        closeness_assessment: 'very close',
        tone_guidance: 'Affectionate and playful without inventing private details.',
        formality: 'casual',
        risk_flags: [],
        agency_slider_default: 0.5,
      },
      human_action: 'accept',
      human_edit: null,
      confidence: 0.95,
      rationale: 'The fixture gives a partner relationship with closeness 5/5.',
      timestamp: '2026-07-06T19:10:10.000Z',
      status: 'completed',
    },
    {
      stage: 'recommendation',
      proposed_by: 'agent',
      output: {
        recommendations: [
          {
            rank: 1,
            category: 'shared experience',
            concept: 'A remote dinner-and-drawing birthday bundle.',
            evidence: ['video dinner memory', 'urban sketching'],
            budget_fit: 'Flexible within the stated budget.',
            artifact_type: 'bundle',
          },
          {
            rank: 2,
            category: 'personalized art',
            concept: 'A Lisbon travel-poster card.',
            evidence: ['urban sketching', 'mustard yellow'],
            budget_fit: 'Digital generation fits the stated budget.',
            artifact_type: 'generated',
          },
          {
            rank: 3,
            category: 'sketching',
            concept: 'A compact urban-sketching travel kit.',
            evidence: ['urban sketching'],
            budget_fit: 'Can be sourced within USD 60-100.',
            artifact_type: 'physical',
          },
        ],
      },
      human_action: 'regenerate',
      human_edit: null,
      confidence: 0.84,
      rationale: 'The first recommendation pass was rerun to emphasize the generated keepsake.',
      timestamp: '2026-07-06T19:10:18.000Z',
      status: 'completed',
    },
    {
      stage: 'recommendation',
      proposed_by: 'agent',
      output: {
        recommendations: [
          {
            rank: 1,
            category: 'personalized art',
            concept: 'A mustard-yellow Lisbon travel-poster birthday card featuring a tram and shared-window motif.',
            evidence: ['urban sketching', 'mustard yellow', 'Lisbon tram memory'],
            budget_fit: 'Digital generation fits the stated budget.',
            artifact_type: 'generated',
          },
          {
            rank: 2,
            category: 'sketching',
            concept: 'A compact urban-sketching travel kit.',
            evidence: ['urban sketching'],
            budget_fit: 'Can be sourced within USD 60-100.',
            artifact_type: 'physical',
          },
          {
            rank: 3,
            category: 'shared experience',
            concept: 'A remote dinner-and-drawing birthday bundle.',
            evidence: ['video dinner memory', 'urban sketching'],
            budget_fit: 'Flexible within the stated budget.',
            artifact_type: 'bundle',
          },
        ],
      },
      human_action: 'delegate',
      human_edit: null,
      confidence: 0.91,
      rationale: 'The ranking connects explicit preferences and shared memories to the birthday.',
      timestamp: '2026-07-06T19:10:28.000Z',
      status: 'completed',
    },
    {
      stage: 'creative_generation',
      proposed_by: 'agent',
      output: {
        artifact_path: '/replay/fixture-long-distance-partners-2026.png',
        artifact_type: 'generated',
        media_type: 'image/png',
        width: 16,
        height: 16,
        agency_slider: 0.5,
        seed: 2026,
        replay_cached: true,
      },
      human_action: 'delegate',
      human_edit: null,
      confidence: null,
      rationale: 'Generated from the fixture memory context at a balanced agency setting.',
      timestamp: '2026-07-06T19:10:35.000Z',
      status: 'completed',
    },
    {
      stage: 'greeting_story',
      proposed_by: 'agent',
      output: {
        message: "Happy birthday, Jordan. From Lisbon's yellow tram to our wonderfully mismatched video dinners, every shared detour feels like home. Here's to the next view we sketch together.",
        memory_references: ['memory-lisbon-tram', 'memory-video-dinner'],
        tone: 'warm and playful',
      },
      human_action: 'delegate',
      human_edit: null,
      confidence: 0.94,
      rationale: 'Uses two supplied memories and follows the close-partner tone guidance.',
      timestamp: '2026-07-06T19:10:39.000Z',
      status: 'completed',
    },
    {
      stage: 'delivery_planner',
      proposed_by: 'agent',
      output: {
        mode: 'digital',
        channel: 'digital card',
        planned_send_date: '2026-09-18',
        occasion_date: '2026-09-18',
        status: 'simulated',
        disclaimer: 'No shipment, purchase, or external delivery was created.',
      },
      human_action: 'delegate',
      human_edit: null,
      confidence: 1,
      rationale: 'Uses simulated digital-card delivery; no purchase or shipment is created.',
      timestamp: '2026-07-06T19:10:42.000Z',
      status: 'completed',
    },
  ],
};
