from __future__ import annotations

import os
from pathlib import Path
from typing import Protocol

import numpy as np
from PIL import Image

from src.gan.infer import MemoryGAN

from .orchestrator import AgentInput, AgentOutput


class ImageGenerator(Protocol):
    def generate(self, **kwargs: object) -> Image.Image: ...


class CreativeGenerationAgent:
    """Generate a visual artifact through MemoryGAN or an optional Diffusers SDXL-Turbo path."""

    stage = "creative_generation"
    _diffusers_pipe = None

    def __init__(self, gan: ImageGenerator) -> None:
        self.gan = gan

    @classmethod
    def from_checkpoint(cls, checkpoint_path: str) -> "CreativeGenerationAgent":
        return cls(MemoryGAN.load(checkpoint_path))

    def run(self, agent_input: AgentInput) -> AgentOutput:
        config = agent_input["stage_config"]
        required = ("context_embedding", "relationship_type", "emotion_tag", "occasion")
        missing = [name for name in required if name not in config]
        if missing:
            raise ValueError(f"creative generation is missing: {', '.join(missing)}")

        agency_slider = float(config.get("agency_slider", 1.0))
        seed = config.get("seed")
        backend = str(config.get("generation_backend") or os.getenv("GMGI_CREATIVE_BACKEND", "memorygan")).lower()
        if backend == "diffusers":
            image = self._generate_with_diffusers(config, seed)
            rationale = "Generated by Diffusers SDXL-Turbo from the gift context and recorded agency setting."
        else:
            image = self.gan.generate(
                context_embedding=np.asarray(config["context_embedding"], dtype=np.float32),
                relationship_type=str(config["relationship_type"]),
                emotion_tag=str(config["emotion_tag"]),
                occasion=str(config["occasion"]),
                agency_slider=agency_slider,
                human_style_ref=(
                    None
                    if config.get("human_style_ref") is None
                    else np.asarray(config["human_style_ref"], dtype=np.float32)
                ),
                seed=None if seed is None else int(seed),
            )
            rationale = "Generated by MemoryGAN from the gift context and recorded agency setting."
        output_dir = Path(config.get("output_dir", "experiments/generated"))
        output_dir.mkdir(parents=True, exist_ok=True)
        filename = str(config.get("filename", f"{agent_input['session'].session_id}.png"))
        artifact_path = output_dir / Path(filename).name
        image.save(artifact_path, format="PNG")
        return AgentOutput(
            stage=self.stage,
            output={
                "artifact_path": artifact_path.as_posix(),
                "artifact_type": "generated",
                "media_type": "image/png",
                "width": image.width,
                "height": image.height,
                "agency_slider": agency_slider,
                "seed": seed,
            },
            confidence=None,
            rationale=rationale,
        )

    def _generate_with_diffusers(self, config: dict[str, object], seed: object) -> Image.Image:
        import torch
        from diffusers import AutoPipelineForText2Image

        if CreativeGenerationAgent._diffusers_pipe is None:
            device = "cuda" if torch.cuda.is_available() else "cpu"
            dtype = torch.float16 if device == "cuda" else torch.float32
            model_id = os.getenv("GMGI_SDXL_MODEL", "stabilityai/sdxl-turbo")
            pipe = AutoPipelineForText2Image.from_pretrained(model_id, torch_dtype=dtype, variant="fp16" if device == "cuda" else None)
            pipe = pipe.to(device)
            CreativeGenerationAgent._diffusers_pipe = pipe
        pipe = CreativeGenerationAgent._diffusers_pipe
        generator = None
        if seed is not None:
            generator = torch.Generator(device=pipe.device).manual_seed(int(seed))
        prompt = str(
            config.get("diffusers_prompt")
            or f"A warm personalized gift illustration for a {config['relationship_type']} relationship, {config['emotion_tag']} mood, {config['occasion']} occasion, refined decorative keepsake style"
        )
        image = pipe(
            prompt=prompt,
            num_inference_steps=int(config.get("num_inference_steps", 1)),
            guidance_scale=float(config.get("guidance_scale", 0.0)),
            generator=generator,
            height=int(config.get("height", 512)),
            width=int(config.get("width", 512)),
        ).images[0]
        return image.convert("RGB")