from __future__ import annotations

from pathlib import Path
from typing import Protocol

import numpy as np
from PIL import Image

from src.gan.infer import MemoryGAN

from .orchestrator import AgentInput, AgentOutput


class ImageGenerator(Protocol):
    def generate(self, **kwargs: object) -> Image.Image: ...


class CreativeGenerationAgent:
    """Generate a visual artifact through the spec-defined MemoryGAN interface."""

    stage = "creative_generation"

    def __init__(self, gan: ImageGenerator) -> None:
        self.gan = gan

    @classmethod
    def from_checkpoint(cls, checkpoint_path: str) -> "CreativeGenerationAgent":
        return cls(MemoryGAN.load(checkpoint_path))

    def run(self, agent_input: AgentInput) -> AgentOutput:
        config = agent_input["stage_config"]
        required = ("context_embedding", "relationship_type", "emotion_tag", "occasion")
        missing = [name for name in required if name not in config]
        if missing:
            raise ValueError(f"creative generation is missing: {', '.join(missing)}")

        agency_slider = float(config.get("agency_slider", 1.0))
        seed = config.get("seed")
        image = self.gan.generate(
            context_embedding=np.asarray(config["context_embedding"], dtype=np.float32),
            relationship_type=str(config["relationship_type"]),
            emotion_tag=str(config["emotion_tag"]),
            occasion=str(config["occasion"]),
            agency_slider=agency_slider,
            human_style_ref=(
                None
                if config.get("human_style_ref") is None
                else np.asarray(config["human_style_ref"], dtype=np.float32)
            ),
            seed=None if seed is None else int(seed),
        )
        output_dir = Path(config.get("output_dir", "experiments/generated"))
        output_dir.mkdir(parents=True, exist_ok=True)
        filename = str(config.get("filename", f"{agent_input['session'].session_id}.png"))
        artifact_path = output_dir / Path(filename).name
        image.save(artifact_path, format="PNG")
        return AgentOutput(
            stage=self.stage,
            output={
                "artifact_path": artifact_path.as_posix(),
                "artifact_type": "generated",
                "media_type": "image/png",
                "width": image.width,
                "height": image.height,
                "agency_slider": agency_slider,
                "seed": seed,
            },
            confidence=None,
            rationale="Generated by MemoryGAN from the fixture memory context and recorded agency setting.",
        )


