from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Protocol

import numpy as np
from PIL import Image

from src.gan.infer import MemoryGAN

from .orchestrator import AgentInput, AgentOutput

CONFIG_DIR = Path(__file__).with_name("configs")


class ImageGenerator(Protocol):
    def generate(self, **kwargs: object) -> Image.Image: ...


class CreativeGenerationAgent:
    """Generate a visual artifact through MemoryGAN or an optional Diffusers SDXL-Turbo path."""

    stage = "creative_generation"
    _diffusers_pipe = None
    _clip_bundle = None

    config_name = "creative_generation.json"

    def __init__(self, gan: ImageGenerator | None = None, *, retriever: Any | None = None, prompt_versions_dir: str | Path | None = None) -> None:
        self.gan = gan
        self.retriever = retriever
        self.config = json.loads((CONFIG_DIR / self.config_name).read_text(encoding="utf-8"))
        self.prompt_version_id = "static"
        self._load_prompt_version(prompt_versions_dir)

    @classmethod
    def from_checkpoint(cls, checkpoint_path: str, *, retriever: Any | None = None, prompt_versions_dir: str | Path | None = None) -> "CreativeGenerationAgent":
        return cls(MemoryGAN.load(checkpoint_path), retriever=retriever, prompt_versions_dir=prompt_versions_dir)

    def run(self, agent_input: AgentInput) -> AgentOutput:
        config = agent_input["stage_config"]
        required = ("context_embedding", "relationship_type", "emotion_tag", "occasion")
        missing = [name for name in required if name not in config]
        if missing:
            raise ValueError(f"creative generation is missing: {', '.join(missing)}")

        agency_slider = float(config.get("agency_slider", 1.0))
        seed = config.get("seed")
        backend = str(config.get("generation_backend") or os.getenv("GMGI_CREATIVE_BACKEND", "memorygan")).lower()
        critique_retries = 0
        clip_score = None
        prompt = self._diffusers_prompt(config)
        if backend == "diffusers":
            max_retries = int(config.get("critique_max_retries", os.getenv("GMGI_CRITIQUE_MAX_RETRIES", "2")))
            threshold = float(config.get("critique_threshold", os.getenv("GMGI_CRITIQUE_THRESHOLD", "0.18")))
            for attempt in range(max(0, max_retries) + 1):
                image = self._generate_with_diffusers(config, seed, prompt=prompt)
                clip_score = self._critique_with_clip(image, prompt)
                if clip_score is None or clip_score >= threshold or attempt >= max_retries:
                    critique_retries = attempt
                    break
                prompt = self._refine_prompt(prompt, config, clip_score)
            rationale = "Generated by Diffusers from the gift context and recorded agency setting."
        else:
            if self.gan is None:
                raise ValueError("MemoryGAN backend requires a loaded GAN checkpoint")
            image = self.gan.generate(
                context_embedding=np.asarray(config["context_embedding"], dtype=np.float32),
                relationship_type=str(config["relationship_type"]),
                emotion_tag=str(config["emotion_tag"]),
                occasion=str(config["occasion"]),
                agency_slider=agency_slider,
                human_style_ref=(
                    None
                    if config.get("human_style_ref") is None
                    else np.asarray(config["human_style_ref"], dtype=np.float32)
                ),
                seed=None if seed is None else int(seed),
            )
            rationale = "Generated by MemoryGAN from the gift context and recorded agency setting."
        if self.prompt_version_id != "static":
            rationale = f"prompt_version={self.prompt_version_id}; {rationale}"
        output_dir = Path(config.get("output_dir", "experiments/generated"))
        output_dir.mkdir(parents=True, exist_ok=True)
        filename = str(config.get("filename", f"{agent_input['session'].session_id}.png"))
        artifact_path = output_dir / Path(filename).name
        image.save(artifact_path, format="PNG")
        return AgentOutput(
            stage=self.stage,
            output={
                "artifact_path": artifact_path.as_posix(),
                "artifact_type": "generated",
                "gift_artifact_type": str(config.get("gift_artifact_type", "greeting_card")),
                "visual_style_prompt": config.get("visual_style_prompt"),
                "media_type": "image/png",
                "width": image.width,
                "height": image.height,
                "agency_slider": agency_slider,
                "seed": seed,
                "diffusers_prompt": prompt if backend == "diffusers" else None,
                "clip_score": clip_score,
                "critique_retries": critique_retries,
                "prompt_version": self.prompt_version_id,
                "skills_used": self._skills_used(backend, clip_score),
            },
            confidence=None,
            rationale=rationale,
        )

    def _generate_with_diffusers(self, config: dict[str, object], seed: object, *, prompt: str | None = None) -> Image.Image:
        import torch
        from diffusers import AutoPipelineForText2Image

        if CreativeGenerationAgent._diffusers_pipe is None:
            device = "cuda" if torch.cuda.is_available() else "cpu"
            dtype = torch.float16 if device == "cuda" else torch.float32
            model_id = os.getenv("GMGI_SDXL_MODEL", "stabilityai/sdxl-turbo")
            pipe = AutoPipelineForText2Image.from_pretrained(model_id, torch_dtype=dtype, variant="fp16" if device == "cuda" else None)
            pipe = pipe.to(device)
            CreativeGenerationAgent._diffusers_pipe = pipe
        pipe = CreativeGenerationAgent._diffusers_pipe
        generator = None
        if seed is not None:
            generator = torch.Generator(device=pipe.device).manual_seed(int(seed))
        prompt = prompt or self._diffusers_prompt(config)
        image = pipe(
            prompt=prompt,
            num_inference_steps=int(config.get("num_inference_steps", 1)),
            guidance_scale=float(config.get("guidance_scale", 0.0)),
            generator=generator,
            height=int(config.get("height", 512)),
            width=int(config.get("width", 512)),
        ).images[0]
        return image.convert("RGB")

    def _diffusers_prompt(self, config: dict[str, object]) -> str:
        supplied = config.get("diffusers_prompt")
        if supplied:
            return self._augment_prompt(str(supplied), config)
        style = config.get("visual_style_prompt") or "personalized gift visual"
        artifact = str(config.get("gift_artifact_type", "greeting_card")).replace("_", " ")
        agency = float(config.get("agency_slider", 0.5))
        human_anchor = "human-specified style cues" if agency < 0.5 else "memory-grounded symbolic details"
        prompt = (
            f"A warm {artifact} for a {config['relationship_type']} relationship, "
            f"{config['emotion_tag']} mood, {config['occasion']} occasion, {style}, {human_anchor}, "
            "print-ready composition, no logos, no readable private text"
        )
        return self._augment_prompt(prompt, config)

    def _refine_prompt(self, prompt: str, config: dict[str, object], score: float) -> str:
        artifact = str(config.get("gift_artifact_type", "greeting_card")).replace("_", " ")
        return (
            f"{prompt}. Refine to make the {artifact} subject more explicit, with clearer occasion symbolism, "
            f"stronger relationship-specific visual cues, and coherent gift presentation. Previous CLIP alignment score: {score:.3f}."
        )

    def _critique_with_clip(self, image: Image.Image, prompt: str) -> float | None:
        if os.getenv("GMGI_DISABLE_CLIP_CRITIC") == "1":
            return None
        try:
            import torch
            import open_clip
        except Exception:
            return None
        try:
            if CreativeGenerationAgent._clip_bundle is None:
                device = "cuda" if torch.cuda.is_available() else "cpu"
                model_name = os.getenv("GMGI_CLIP_MODEL", "ViT-B-32")
                pretrained = os.getenv("GMGI_CLIP_PRETRAINED", "openai")
                model, _, preprocess = open_clip.create_model_and_transforms(model_name, pretrained=pretrained, device=device)
                tokenizer = open_clip.get_tokenizer(model_name)
                model.eval()
                CreativeGenerationAgent._clip_bundle = (model, preprocess, tokenizer, device)
            model, preprocess, tokenizer, device = CreativeGenerationAgent._clip_bundle
            with torch.no_grad():
                image_tensor = preprocess(image).unsqueeze(0).to(device)
                text_tokens = tokenizer([prompt]).to(device)
                image_features = model.encode_image(image_tensor)
                text_features = model.encode_text(text_tokens)
                image_features = image_features / image_features.norm(dim=-1, keepdim=True)
                text_features = text_features / text_features.norm(dim=-1, keepdim=True)
                score = (image_features @ text_features.T).item()
            return float(max(0.0, min(1.0, (score + 1.0) / 2.0)))
        except Exception:
            return None

    def _augment_prompt(self, prompt: str, config: dict[str, object]) -> str:
        guidance = str(self.config.get("system_prompt", "")).strip()
        context_fp = str(config.get("context_fingerprint") or "")
        if self.retriever is not None and context_fp:
            guidance = self.retriever.augment_system_prompt(self.stage, guidance, context_fp)
        return f"{guidance}\n\nVisual prompt:\n{prompt}" if guidance else prompt

    def _load_prompt_version(self, prompt_versions_dir: str | Path | None) -> None:
        root_value = prompt_versions_dir or os.getenv("GMGI_PROMPT_VERSIONS")
        root = Path(root_value) if root_value else CONFIG_DIR / "prompt_versions"
        latest = root / self.stage / "latest.json"
        if not latest.exists():
            return
        payload = json.loads(latest.read_text(encoding="utf-8"))
        prompt = payload.get("system_prompt") or payload.get("prompt")
        if isinstance(prompt, str) and prompt.strip():
            self.config["system_prompt"] = prompt
            self.prompt_version_id = str(payload.get("version_id") or latest.as_posix())

    @staticmethod
    def _skills_used(backend: str, clip_score: float | None) -> list[str]:
        skills = ["visual_prompt_builder", backend]
        if clip_score is not None:
            skills.append("clip_critic")
        return skills

